### ISSUE TITLE
submit patches back to simsong/bulk_extractor

### ISSUE THREAD

**Issue by simsong** [4n6ist/bulk_extractor-rec#1]
Hi. Are there plans to submit patches back to the main bulk_extractor project? Some users are confused by the existence of this fork and have contacted me, asking your plans.

**Comment by 4n6ist** [comment]
Hello, I'm sorry it totally slipped my mind..I think some plugins are stable but a lot of time have already passed. I will confirm and submit to main repository, so please give me time for a while.

**Comment by simsong** [comment]
It may be easier to simply identify the significant advances and separately migrate them into the current code base. I'll try to do a diff of the two repos...

**Comment by simsong** [comment]
It looks like every line of the manual is reported as changed because you added ^M's to the end of every line. I recommend fixing all of your line endings... If you want, I can do that and send you a pull request.

**Comment by 4n6ist** [comment]
OK! please send me a pull request.

**Comment by simsong** [comment]
Okay, the line ending problems that I identified were actually in the simsong/bulk_extractor repository, and specifically in the doc/latex_manuals directory, so they were probably there for a *long* time. I just fixed them. 

I've looked over your code and it seems that the main thing that you've done is written some new scanners. I don't see any deep architectural changes.  

I contacted you because someone contacted me asking if we were going to do anything with your scanners, as they would like to use the scanners. I'm happy to incorporate them. Do you have test files for the various scanners that you wrote? What sort of test infrastructure did you use?

I've been given a request to bring out a new version of bulk_extractor as soon as possible, using the up-to-date dfxml package and making it work with a modern OpenSSL. So I'm going to need to do that. I think that it then makes sense to just manually port your scanners over, rather than attempting a git merge. What do you think?

**Comment by 4n6ist** [comment]
Thank you for your time.

> Okay, the line ending problems that I identified were actually in the simsong/bulk_extractor repository, and specifically in the doc/latex_manuals directory, so they were probably there for a _long_ time. I just fixed them.

OK, I understood.

> I've looked over your code and it seems that the main thing that you've done is written some new scanners. I don't see any deep architectural changes.
> 
> I contacted you because someone contacted me asking if we were going to do anything with your scanners, as they would like to use the scanners. I'm happy to incorporate them. Do you have test files for the various scanners that you wrote? What sort of test infrastructure did you use?

I see. I also want these scanners to be included in your repository. I committed some scanners I implemented to simsong/bulk_extractor in Jan 2018, and remaining what I think it's stable and I would like to submit are as follows.

(src/)
- scan_evtx.cpp
- scan_ntfsindx.cpp
- scan_ntfslogfile.cpp
- scan_ntfsmft.cpp
- scan_utmp.cpp

I don't have any specific test files, sorry. I just utilized a lot of data on my cases. I also tried several images publicly available such as LoneWolf at digitalcorpora and DefCon DFIR CTF. When I have time, I may be able to prepare for small sample like simsong/bulk_extractor/tests/Images/.
 
> I've been given a request to bring out a new version of bulk_extractor as soon as possible, using the up-to-date dfxml package and making it work with a modern OpenSSL. So I'm going to need to do that. I think that it then makes sense to just manually port your scanners over, rather than attempting a git merge. What do you think?

That's great! I think it's enough to port(copy) above files manually to your repository. 

If there's anything other I can do for you, please let me know.

**Comment by simsong** [comment]
Okay. That's an easy task! I'll copy those scanners over now. How would you like me to give you credit for the work? Do you have any documentation or other stuff that you would like me to add?

**Comment by simsong** [comment]
Okay, I've got the scanners integrated into the code base and I'm now running all the regression tests. They will be in the next release of bulk_extractor, which hopefully will be by Monday. Thanks for your help!

**Comment by 4n6ist** [comment]
Thanks a lot!
If you don't mind, I would like to include author "Teru Yamazaki(@4n6ist)" and a link for my slide at OSDFCon 2018
http://www.osdfcon.org/presentations/2018/Teru-Yamazaki-A-Combination-of-Advanced-Carver-and-Intelligent-Parser.pdf

**Comment by simsong** [comment]
That’s great. Would you be able to help test the release? It is currently on GitHub.

**Comment by 4n6ist** [comment]
Sure. I will try when I have time!

**Comment by simsong** [comment]
It would be my preference to simply add the PDF to the doc/ directory. Any objection?

**Comment by 4n6ist** [comment]
Of course not. Thank you!

**Comment by 4n6ist** [comment]
I have tried to test the latest code on your repository (simsong/bulk_extractor, commit: 279bba3644eca63146df0836e187c8668d48b8e4), but it seems the binary I built doesn't include my scanners even though the source codes are located in src directory.

What I tried is the following steps on Ubuntu 18.04:

> apt-get install git
> git clone --recursive git@github.com:simsong/bulk_extractor.git
> cd bulk_extractor
> bash etc/CONFIGURE_UBUNTU18.bash
> bootstrap.sh
> ./configure
> make && sudo make install

Anything I'm overlooking?

**Comment by simsong** [comment]
Thanks! Let me check it out. I probably forgot to add them to the scanner list. It's been several years since I added a new scanner.

**Comment by simsong** [comment]
Okay, I got it working again. Unfortunately, I went on vacation without pushing the commit from my desktop back to Github! Sorry about that; it will be pushed on December 2nd.

**Comment by 4n6ist** [comment]
Never mind. I will try it when it will be available!

**Comment by simsong** [comment]
The current release of bulk_extractor now includes your contributions. Thank you!
